### PR TITLE
Enable travis builds.

### PR DESCRIPTION
**Pull request by matthayter**
... by adding a skeleton Rakefile and copying in the JSON schema for test usage.

### CODE REVIEW

**Comment by vjkoskela** [comment]
Those schema files need to come from a resource package. It looks like they've already been copied into the metrics client -- @BrandonArp? Assuming you don't want to tackle this now, please file issues against both projects to use a shared package with the schemas.

**Comment by BrandonArp** [comment]
@vjkoskela Care to explain how to have a shared package with a ruby build?  Also, the schema files are locked, immutable.  I don't see any problem with copying them here.

**Comment by vjkoskela** [comment]
@BrandonArp Sure. I have three options, I don't like any of them but hopefully you guys can see either how to improve on them or maybe they will inspire option four. Before I dig into these, those schema files are not strictly immutable. We have in the past found bugs in the schema and those have been addressed with changes instead of new versions. They also include documentation of the schema and examples, and new versions will be created in the future. This will be a problem keeping them all up to date; maybe not the biggest problem, but a problem nonetheless.

Here are my suggestions:

Option 1 - Multiple Native Packages from Single Source - Just as ugly as it sounds, one project which from the same source creates: i) Maven Artifact, ii) Ruby GEM, iii) NPM Package. All three are published every build and versioned. The advantages are versioned artifacts for the schema, the downside is a custom build process (and probably a rather hairy one at that) -- although it's encapsulated in a single project, it will be touched every time we add a new client binding.

Option 2 - Single Package and Custom Consumption - We select one package type (e.g. Maven Artifact) and then publish only to that creating pre-build bindings to pull and unpack that package in other languages. Whatever the package type should be the easiest to work with from scripts so that the downloading and unpacking are the least painful. This seems like the worst solution (to me at least) since it spreads the ugliness across N-1 client libraries and requires hacky-hacky in any new language bindings to incorporate the package to that binding.

Option 3 - Submodules - Instead of worrying about resource packages we just hard-link a common metrics-client-docs repository into the language specific repositories. The submodule link is SHA specific so it would be "versioned"; however, it does present some maintenance issues in my opinion. The big pro here is that it gets around both the copying of these resources and the bundling of them into package(s).

I have had horrible experiences with submodules, this was a pretty good summary that matches my experiences:

https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/

However, perhaps they have improved since 2012. Here are some other resources, as much as it makes me feel queasy submodules may be the most immediate solution to this.

https://chrisjean.com/git-submodules-adding-using-removing-and-updating/

Let me know what you guys think.

**Comment by tmack8001** [comment]
I would prefer working with submodules myself, but yes setting them up with little to no experience can be painful. I love the idea of them and the concept of just referencing another SHA directly, but they are a little tricky at time. This path is also the least amount of change that would need to be put in place to start so that is also a good thing and if we decide another direction is better it is fairly simple to remove and replace with another solution without undue artifacts or setup laying around somewhere else.

FYI: That blog post does a great job documenting how most people probably use submodules anyways and some of the pain points they might cause people (nice find).

**Comment by vjkoskela** [comment]
## General

In this case I _believe_ the desired behavior is to actually always reference the latest version of a particular schema. The schemas themselves are already versioned, in that there is a separate schema file for each version. Further, we continue to support old versions so they should be removed until support for a particular schema version is discontinued. 

These schemas are for an internal file format and are (again in my opinion) equivalent to test assertions for the client libraries expressed in a language/framework independent way.

Those "assertions" can have bugs (e.g. be specified incorrectly). Changing overly strict schema to be more permissive is always safe. Changing overly permissive schema to be more strict can identify clients that have tests for cases where unparsable or unsupported data is generated (via test failure).

## Submodules

Submodules do not make this easy because they reference a particular SHA and because it requires manual steps to change and commit a change to this SHA. Of course, always obtaining the latest version has the drawback that if someone fixes a _bug_ in the specification then that can cause 1) a build to not be repeatable, and 2) block the next release. 

However, the benefit is that if a bug is found in the schema (e.g. the schema is _mistakenly_ too permissive compared to the intent and implementation) that a change in the schema will identify any clients and block subsequent releases until the client conforms. All the schema changes we have had have involved this type of change but have never lead to blocking client changes (e.g. no client ever produced the data in the misspecification).

## Alternative

Submodules are one of the easiest ways to implement this and I would love to hear how some of those procedural drawbacks could be overcome or worked around (or even how we see this is _wrong_). The fourth alternative we have discussed is having the specifications available in a third repository (e.g. metrics-client-doc). The unit tests in each client can wget (and even cache as fallback) the version of the schema they are using. 

In the Java client the minimal change is one line:

``` java
jsonNode = JsonLoader.fromPath("../doc/query-log-schema-2e.json");
```

to:

``` java
jsonNode = JsonLoader.fromUrl("https://github.com/ArpNetworking/metrics-client-doc/blob/master/doc/query-log-schema-2e.json.md");
```

To cache the remote copy would take a little more. Namely, saving it on each remote read and falling back to the cached copy on remote read failures. This seems pretty minimal and non-intrusive to developers and absolves any need for manual intervention when backfilling a schema bug.

## Conclusion

There is definitely a trade-off here between competing factors. @matthayter presented some very arguments to strongly version these documents. Those arguments are not wrong, but I am not convinced they make the appropriate trade-off in this context. Are there other opinions along these lines as to what is the appropriate trade-off in distributing these schema files to clients for testing?

**Pull request merged**
